version: '3.8'

services:
  web:
    image: 940622738555.dkr.ecr.us-east-1.amazonaws.com/flask-mysql:latest

    ports:
      - "5002:5002"
    depends_on:
      - mydb2

  mydb2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw